try {

  alert('Awal proses mencoba nih');  // (1) <--

  // ...no errors here

  alert('Akhir proses mencoba yeaay');   // (2) <--

} catch(err) {

  alert('Tangkapan diabaikan, karena tidak ada kesalahan. Okeey'); // (3)

}